services:
  flask:
    build:
      args:
        PIP_REQUIREMENTS: requirements/prod.txt
    expose:
      - 8001
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp1.rule=Host(`${PORTAL_HOST}`)"
      - "traefik.http.routers.myapp1.entrypoints=websecure"
      - "traefik.http.routers.myapp1.tls.certresolver=myresolver"
      - "traefik.http.services.flask.loadbalancer.server.port=8001"
    volumes:
      - ..naturedb-volumes/logs/flask:/app/logs

  postgres:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ..naturedb-volumes/logs/postgres:/var/log/postgresql
      - ./docker/postgresql.conf:/etc/postgresql.conf
      #command: -c config_file=/etc/postgresql.conf
  redis:
    restart: always

  traefik:
    image: traefik:3.6
    restart: always
    environment:
      - CF_DNS_API_TOKEN=`${CF_DNS_API_TOKEN}`
      # Optional: Explicitly tell LEGO (the underlying library) to follow CNAMEs
      - LEGO_EXPERIMENTAL_CNAME_SUPPORT=true
    command:
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      #- "--certificatesresolvers.myresolver.acme.tlsChallenge=true"
      #- "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      #- --certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1:53
      # Use public resolvers to ensure Traefik sees the CNAME quickly
      - "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"

      - "--accesslog.filePath=/logs/access.log"
      - "--accesslog.bufferingsize=100"
      - "--accesslog.format=json"
      - "--accesslog.addinternals"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
      - ../naturedb-volumes/logs/traefik:/logs
