services:
  flask:
    build:
      args:
        PIP_REQUIREMENTS: requirements/prod.txt
    expose:
    - 8001
    restart: always

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - flask
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      #- ../naturedb-volumes/static:/naturedb-volumes/static
      #- ../naturedb-volumes/admin:/naturedb-volumes/admin
      - ../naturedb-volumes/bucket:/bucket
      - ../naturedb-volumes/certbot/conf:/etc/letsencrypt
      - ../naturedb-volumes/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ../naturedb-volumes/certbot/conf:/etc/letsencrypt
      - ../naturedb-volumes/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  postgres:
    restart: always
  redis:
    restart: always
  # traefik:
  #   image: traefik:v2.7
  #   command:
  #     - --api.insecure=true
  #     - --providers.docker
  #     - --entryPoints.web.address=:80
  #     - --providers.docker.exposedByDefault=false
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
