"""try

Revision ID: 0a3926f4843e
Revises: 3e47697ad7d6
Create Date: 2023-12-03 18:41:50.518143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3926f4843e'
down_revision = '3e47697ad7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
