"""collection-sort

Revision ID: 1071a2088401
Revises: 7f2197958568
Create Date: 2024-01-04 19:34:34.933465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1071a2088401'
down_revision = '7f2197958568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('sort', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'sort')
    # ### end Alembic commands ###
