"""propagation

Revision ID: 1fd9fdd0f070
Revises: 9096d76041b9
Create Date: 2023-12-21 07:03:46.492166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd9fdd0f070'
down_revision = '9096d76041b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propagation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propagation_type', sa.String(length=50), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propagation')
    # ### end Alembic commands ###
