"""collection-layer

Revision ID: 21b530bbce0a
Revises: 1b6142470a6b
Create Date: 2024-12-13 01:28:42.355024

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '21b530bbce0a'
down_revision = '1b6142470a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collection', 'collection', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_column('collection', 'parent_id')
    # ### end Alembic commands ###
