"""person-remark

Revision ID: 23812df96b5f
Revises: 4d90cdf19c8c
Create Date: 2024-12-06 07:48:47.809086

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '23812df96b5f'
down_revision = '4d90cdf19c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('remark', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'remark')
    # ### end Alembic commands ###
