"""geonames

Revision ID: 242c03df73fc
Revises: a8963344cf1f
Create Date: 2024-02-04 02:53:04.282941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242c03df73fc'
down_revision = 'a8963344cf1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addon_geoname',
    sa.Column('geonameid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('asciiname', sa.String(length=500), nullable=True),
    sa.Column('alternatenames', sa.Text(), nullable=True),
    sa.Column('latitude', sa.String(length=500), nullable=True),
    sa.Column('longitude', sa.String(length=500), nullable=True),
    sa.Column('feature_class', sa.String(length=500), nullable=True),
    sa.Column('feature_code', sa.String(length=500), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('cc2', sa.String(length=500), nullable=True),
    sa.Column('admin1_code', sa.String(length=500), nullable=True),
    sa.Column('admin2_code', sa.String(length=500), nullable=True),
    sa.Column('admin3_code', sa.String(length=500), nullable=True),
    sa.Column('admin4_code', sa.String(length=500), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.Column('dem', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=500), nullable=True),
    sa.Column('modification_date', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('geonameid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addon_geoname')
    # ### end Alembic commands ###
