"""datum

Revision ID: 260e33819b5e
Revises: 7c5e4368cbef
Create Date: 2024-06-12 16:19:57.029394

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '260e33819b5e'
down_revision = '7c5e4368cbef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('geodetic_datum', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'geodetic_datum')
    # ### end Alembic commands ###
