"""delete-mo-cat

Revision ID: 280914e94b3e
Revises: 65a3814bda81
Create Date: 2023-12-27 09:38:37.881119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280914e94b3e'
down_revision = '65a3814bda81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multimedia_object_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multimedia_object_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='multimedia_object_category_pkey')
    )
    # ### end Alembic commands ###
