"""unit-verbatim

Revision ID: 2c73036fd87f
Revises: 90f09a2dab52
Create Date: 2025-12-24 02:21:21.404313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '2c73036fd87f'
down_revision = '90f09a2dab52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_verbatim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_verbatim_section_type'), 'unit_verbatim', ['section_type'], unique=False)
    op.create_index(op.f('ix_unit_verbatim_source_type'), 'unit_verbatim', ['source_type'], unique=False)
    op.create_index(op.f('ix_unit_verbatim_unit_id'), 'unit_verbatim', ['unit_id'], unique=False)
    op.create_index(op.f('ix_unit_verbatim_user_id'), 'unit_verbatim', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_verbatim_user_id'), table_name='unit_verbatim')
    op.drop_index(op.f('ix_unit_verbatim_unit_id'), table_name='unit_verbatim')
    op.drop_index(op.f('ix_unit_verbatim_source_type'), table_name='unit_verbatim')
    op.drop_index(op.f('ix_unit_verbatim_section_type'), table_name='unit_verbatim')
    op.drop_table('unit_verbatim')
    # ### end Alembic commands ###
