"""org.ark_nam

Revision ID: 2d06cf9ce61d
Revises: 9946472227e4
Create Date: 2023-12-14 22:54:21.551095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d06cf9ce61d'
down_revision = '9946472227e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('ark_nam', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'ark_nam')
    # ### end Alembic commands ###
