"""record-group-map-cascade

Revision ID: 2d3ac4882c24
Revises: b4b59f3d2961
Create Date: 2025-06-30 14:02:52.712786

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '2d3ac4882c24'
down_revision = 'b4b59f3d2961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('record_group_map_record_id_fkey', 'record_group_map', type_='foreignkey')
    op.create_foreign_key(None, 'record_group_map', 'record', ['record_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unit_parent_id_fkey', 'unit', type_='foreignkey')
    op.create_foreign_key(None, 'unit', 'unit', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.create_foreign_key('unit_parent_id_fkey', 'unit', 'unit', ['parent_id'], ['id'])
    op.drop_constraint(None, 'record_group_map', type_='foreignkey')
    op.create_foreign_key('record_group_map_record_id_fkey', 'record_group_map', 'record', ['record_id'], ['id'])
    # ### end Alembic commands ###
