"""dns

Revision ID: 318dcd16a600
Revises: 260e33819b5e
Create Date: 2024-06-17 18:13:43.120105

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '318dcd16a600'
down_revision = '260e33819b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('basis_of_record', sa.String(length=50), nullable=True))
    op.add_column('unit', sa.Column('material_entity_id', sa.String(length=500), nullable=True))
    op.add_column('unit', sa.Column('dna_sequence', sa.Text(), nullable=True))
    op.add_column('unit', sa.Column('sequencer', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'sequencer')
    op.drop_column('unit', 'dna_sequence')
    op.drop_column('unit', 'material_entity_id')
    op.drop_column('unit', 'basis_of_record')
    # ### end Alembic commands ###
