"""add geological context fields to record

Revision ID: 3225bc4e3243
Revises: e5f6a7b8c9d0
Create Date: 2026-03-04 18:58:22.359688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3225bc4e3243'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('earliest_eon_or_lowest_eonothem', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('latest_eon_or_highest_eonothem', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('earliest_era_or_lowest_erathem', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('latest_era_or_highest_erathem', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('earliest_period_or_lowest_system', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('latest_period_or_highest_system', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('earliest_epoch_or_lowest_series', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('latest_epoch_or_highest_series', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('earliest_age_or_lowest_stage', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('latest_age_or_highest_stage', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('lowest_biostratigraphic_zone', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('highest_biostratigraphic_zone', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('lithostratigraphic_terms', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('geological_context_group', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('formation', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('member', sa.String(length=500), nullable=True))
    op.add_column('record', sa.Column('bed', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'bed')
    op.drop_column('record', 'member')
    op.drop_column('record', 'formation')
    op.drop_column('record', 'geological_context_group')
    op.drop_column('record', 'lithostratigraphic_terms')
    op.drop_column('record', 'highest_biostratigraphic_zone')
    op.drop_column('record', 'lowest_biostratigraphic_zone')
    op.drop_column('record', 'latest_age_or_highest_stage')
    op.drop_column('record', 'earliest_age_or_lowest_stage')
    op.drop_column('record', 'latest_epoch_or_highest_series')
    op.drop_column('record', 'earliest_epoch_or_lowest_series')
    op.drop_column('record', 'latest_period_or_highest_system')
    op.drop_column('record', 'earliest_period_or_lowest_system')
    op.drop_column('record', 'latest_era_or_highest_erathem')
    op.drop_column('record', 'earliest_era_or_lowest_erathem')
    op.drop_column('record', 'latest_eon_or_highest_eonothem')
    op.drop_column('record', 'earliest_eon_or_lowest_eonothem')
    # ### end Alembic commands ###
