"""record_group-rm-org-id

Revision ID: 334ff7172057
Revises: 21b530bbce0a
Create Date: 2024-12-20 09:05:06.582646

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '334ff7172057'
down_revision = '21b530bbce0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('record_group_organization_id_fkey', 'record_group', type_='foreignkey')
    op.drop_column('record_group', 'organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_group', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('record_group_organization_id_fkey', 'record_group', 'organization', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
