"""site-rm-code

Revision ID: 3785ccd6eb37
Revises: 3da76abfc432
Create Date: 2024-06-18 05:19:48.455171

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '3785ccd6eb37'
down_revision = '3da76abfc432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('code', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
