"""ark

Revision ID: 3e47697ad7d6
Revises: 949e80326457
Create Date: 2023-08-25 00:45:15.900623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e47697ad7d6'
down_revision = '949e80326457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pid_ark_naan',
    sa.Column('naan', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('naan')
    )
    op.create_table('pid_ark',
    sa.Column('identifier', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('naan', sa.Integer(), nullable=True),
    sa.Column('who', sa.String(length=500), nullable=True),
    sa.Column('what', sa.String(length=500), nullable=True),
    sa.Column('when', sa.String(length=500), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['naan'], ['pid_ark_naan.naan'], ),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('pid_ark_shoulder',
    sa.Column('shoulder', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('naan', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['naan'], ['pid_ark_naan.naan'], ),
    sa.PrimaryKeyConstraint('shoulder')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pid_ark_shoulder')
    op.drop_table('pid_ark')
    op.drop_table('pid_ark_naan')
    # ### end Alembic commands ###
