"""host

Revision ID: 4c228755cffb
Revises: aef30cda76fc
Create Date: 2024-06-18 02:51:58.696708

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '4c228755cffb'
down_revision = 'aef30cda76fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('host', sa.String(length=500), nullable=True))
    op.drop_column('site', 'domain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('domain', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('site', 'host')
    # ### end Alembic commands ###
