"""user-list-created

Revision ID: 4d90cdf19c8c
Revises: 50c149e49827
Create Date: 2024-11-29 17:26:09.520656

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '4d90cdf19c8c'
down_revision = '50c149e49827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_list', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_list', 'created')
    # ### end Alembic commands ###
