"""record-list2

Revision ID: 4df725b4d78d
Revises: 1b23ffd0716b
Create Date: 2024-01-25 17:30:51.550169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df725b4d78d'
down_revision = '1b23ffd0716b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
