"""add-media-guid

Revision ID: 50c149e49827
Revises: bd8fe670a01d
Create Date: 2024-11-06 03:28:22.861377

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '50c149e49827'
down_revision = 'bd8fe670a01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multimedia_object', sa.Column('guid', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('multimedia_object', 'guid')
    # ### end Alembic commands ###
