"""model-history-user-id

Revision ID: 541700092a8e
Revises: 0a3926f4843e
Create Date: 2023-12-03 18:42:45.986510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541700092a8e'
down_revision = '0a3926f4843e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
