"""collection-site-id

Revision ID: 54844ef10da8
Revises: c80f91a5fba6
Create Date: 2024-06-19 10:11:44.863294

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '54844ef10da8'
down_revision = 'c80f91a5fba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collection', 'site', ['site_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_column('collection', 'site_id')
    # ### end Alembic commands ###
