"""add is_external to taxon_tree

Revision ID: 582f972a840e
Revises: 7b2e4c91a3d8
Create Date: 2026-03-23 20:15:26.162446

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '582f972a840e'
down_revision = '7b2e4c91a3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxon_tree', sa.Column('is_external', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxon_tree', 'is_external')
    # ### end Alembic commands ###
