"""add person atomized columns and preferred_name

Revision ID: 5a005bedbbbc
Revises: 74ee974ad375
Create Date: 2026-03-03 07:35:15.232576

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '5a005bedbbbc'
down_revision = '74ee974ad375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('given_name', sa.String(length=500), nullable=True))
    op.add_column('person', sa.Column('inherited_name', sa.String(length=500), nullable=True))
    op.add_column('person', sa.Column('given_name_en', sa.String(length=500), nullable=True))
    op.add_column('person', sa.Column('inherited_name_en', sa.String(length=500), nullable=True))
    op.add_column('person', sa.Column('preferred_name', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'preferred_name')
    op.drop_column('person', 'inherited_name_en')
    op.drop_column('person', 'given_name_en')
    op.drop_column('person', 'inherited_name')
    op.drop_column('person', 'given_name')
    # ### end Alembic commands ###
