"""remove-fav

Revision ID: 5a4e00abaf48
Revises: 4df725b4d78d
Create Date: 2024-01-25 17:34:40.442122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4e00abaf48'
down_revision = '4df725b4d78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('record', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='favorite_pkey')
    )
    # ### end Alembic commands ###
