"""add formation_en to record_geological_context

Revision ID: 5cc2cedf7d7f
Revises: f41778c0817e
Create Date: 2026-03-13 06:57:05.072675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '5cc2cedf7d7f'
down_revision = 'f41778c0817e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_geological_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('earliest_geochronologic', sa.String(length=500), nullable=True),
    sa.Column('earliest_geochronologic_prefix', sa.String(length=50), nullable=True),
    sa.Column('latest_geochronologic', sa.String(length=500), nullable=True),
    sa.Column('latest_geochronologic_prefix', sa.String(length=50), nullable=True),
    sa.Column('lowest_biostratigraphic_zone', sa.String(length=500), nullable=True),
    sa.Column('highest_biostratigraphic_zone', sa.String(length=500), nullable=True),
    sa.Column('lithostratigraphic_terms', sa.String(length=500), nullable=True),
    sa.Column('geological_context_group', sa.String(length=500), nullable=True),
    sa.Column('formation', sa.String(length=500), nullable=True),
    sa.Column('formation_en', sa.String(length=500), nullable=True),
    sa.Column('member', sa.String(length=500), nullable=True),
    sa.Column('bed', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    op.drop_column('record', 'earliest_geochronologic_prefix')
    op.drop_column('record', 'lowest_biostratigraphic_zone')
    op.drop_column('record', 'latest_geochronologic_prefix')
    op.drop_column('record', 'member')
    op.drop_column('record', 'highest_biostratigraphic_zone')
    op.drop_column('record', 'bed')
    op.drop_column('record', 'latest_geochronologic')
    op.drop_column('record', 'earliest_geochronologic')
    op.drop_column('record', 'formation')
    op.drop_column('record', 'lithostratigraphic_terms')
    op.drop_column('record', 'geological_context_group')
    op.drop_column('record_person', 'role')
    op.add_column('taxon_tree', sa.Column('hierarchy', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxon_tree', 'hierarchy')
    op.add_column('record_person', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('record', sa.Column('geological_context_group', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('record', sa.Column('lithostratigraphic_terms', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('record', sa.Column('formation', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('record', sa.Column('earliest_geochronologic', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('record', sa.Column('latest_geochronologic', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('record', sa.Column('bed', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('record', sa.Column('highest_biostratigraphic_zone', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('record', sa.Column('member', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('record', sa.Column('latest_geochronologic_prefix', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('record', sa.Column('lowest_biostratigraphic_zone', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('record', sa.Column('earliest_geochronologic_prefix', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_table('record_geological_context')
    # ### end Alembic commands ###
