"""user-list-category

Revision ID: 5eb6d18e0c1e
Revises: cc5779d1062b
Create Date: 2024-01-25 19:44:46.676639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb6d18e0c1e'
down_revision = 'cc5779d1062b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_list', sa.Column('user_list_category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_list', 'user_list_category', ['user_list_category'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_list', type_='foreignkey')
    op.drop_column('user_list', 'user_list_category')
    # ### end Alembic commands ###
