"""taxon-add-index

Revision ID: 60df15f0646f
Revises: b34921972c96
Create Date: 2024-03-27 07:23:38.301304

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '60df15f0646f'
down_revision = 'b34921972c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_taxon_full_scientific_name'), 'taxon', ['full_scientific_name'], unique=False)
    op.create_index(op.f('ix_taxon_rank'), 'taxon', ['rank'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxon_rank'), table_name='taxon')
    op.drop_index(op.f('ix_taxon_full_scientific_name'), table_name='taxon')
    # ### end Alembic commands ###
