"""refactor-media-license

Revision ID: 65a3814bda81
Revises: a1bf58983c76
Create Date: 2023-12-27 08:55:57.534930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a3814bda81'
down_revision = 'a1bf58983c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multimedia_object_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multimedia_object_physical_format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multimedia_object_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('multimedia_object_category')
    op.add_column('multimedia_object', sa.Column('type_id', sa.Integer(), nullable=True))
    op.add_column('multimedia_object', sa.Column('physical_format_id', sa.Integer(), nullable=True))
    op.add_column('multimedia_object', sa.Column('context_id', sa.Integer(), nullable=True))
    op.add_column('multimedia_object', sa.Column('legal_statement_id', sa.Integer(), nullable=True))
    op.drop_constraint('multimedia_object_category_id_fkey', 'multimedia_object', type_='foreignkey')
    op.create_foreign_key(None, 'multimedia_object', 'multimedia_object_type', ['type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'multimedia_object', 'legal_statement', ['legal_statement_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'multimedia_object', 'multimedia_object_context', ['context_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'multimedia_object', 'multimedia_object_physical_format', ['physical_format_id'], ['id'], ondelete='SET NULL')
    op.drop_column('multimedia_object', 'physical_format')
    op.drop_column('multimedia_object', 'context')
    op.drop_column('multimedia_object', 'category_id')
    op.drop_column('multimedia_object', 'multimedia_type')
    op.drop_column('multimedia_object', 'license')
    op.add_column('unit', sa.Column('legal_statement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unit', 'legal_statement', ['legal_statement_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.drop_column('unit', 'legal_statement_id')
    op.add_column('multimedia_object', sa.Column('license', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('multimedia_object', sa.Column('multimedia_type', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('multimedia_object', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('multimedia_object', sa.Column('context', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('multimedia_object', sa.Column('physical_format', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'multimedia_object', type_='foreignkey')
    op.drop_constraint(None, 'multimedia_object', type_='foreignkey')
    op.drop_constraint(None, 'multimedia_object', type_='foreignkey')
    op.drop_constraint(None, 'multimedia_object', type_='foreignkey')
    op.create_foreign_key('multimedia_object_category_id_fkey', 'multimedia_object', 'multimedia_object_category', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('multimedia_object', 'legal_statement_id')
    op.drop_column('multimedia_object', 'context_id')
    op.drop_column('multimedia_object', 'physical_format_id')
    op.drop_column('multimedia_object', 'type_id')
    op.create_table('multimedia_object_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='multimedia_object_category_pkey')
    )
    op.drop_table('multimedia_object_type')
    op.drop_table('multimedia_object_physical_format')
    op.drop_table('multimedia_object_context')
    op.drop_table('legal_statement')
    # ### end Alembic commands ###
