"""add-geom

Revision ID: 675f3d3e99af
Revises: fb2dd663057f
Create Date: 2024-02-23 18:36:09.844916

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '675f3d3e99af'
down_revision = 'fb2dd663057f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column('named_area', sa.Column('geom_mpoly', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_geospatial_index('idx_named_area_geom_mpoly', 'named_area', ['geom_mpoly'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_named_area_geom_mpoly', table_name='named_area', postgresql_using='gist', column_name='geom_mpoly')
    op.drop_geospatial_column('named_area', 'geom_mpoly')
    # ### end Alembic commands ###
