"""assertion-option-id

Revision ID: 686394455b1e
Revises: e508c32e9e09
Create Date: 2024-10-16 03:52:27.765874

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '686394455b1e'
down_revision = 'e508c32e9e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_assertion', sa.Column('option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'record_assertion', 'assertion_type_option', ['option_id'], ['id'])
    op.drop_constraint('record_named_area_map_record_id_fkey', 'record_named_area_map', type_='foreignkey')
    op.create_foreign_key(None, 'record_named_area_map', 'record', ['record_id'], ['id'])
    op.add_column('unit_assertion', sa.Column('option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unit_assertion', 'assertion_type_option', ['option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit_assertion', type_='foreignkey')
    op.drop_column('unit_assertion', 'option_id')
    op.drop_constraint(None, 'record_named_area_map', type_='foreignkey')
    op.create_foreign_key('record_named_area_map_record_id_fkey', 'record_named_area_map', 'record', ['record_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'record_assertion', type_='foreignkey')
    op.drop_column('record_assertion', 'option_id')
    # ### end Alembic commands ###
