"""verbatim

Revision ID: 6b13e0d7e5d3
Revises: f64687dde625
Create Date: 2023-01-29 20:27:25.636758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b13e0d7e5d3'
down_revision = 'f64687dde625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identification', sa.Column('verbatim_identification', sa.String(length=500), nullable=True))
    op.add_column('identification', sa.Column('verbatim_date', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identification', 'verbatim_date')
    op.drop_column('identification', 'verbatim_identification')
    # ### end Alembic commands ###
