"""remove unit.verbatim_label

Revision ID: 74ee974ad375
Revises: 2c73036fd87f
Create Date: 2025-12-24 03:16:01.442042

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '74ee974ad375'
down_revision = '2c73036fd87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'verbatim_label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('verbatim_label', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
