"""org-domain

Revision ID: 76c4477e5623
Revises: a4d050f81a5a
Create Date: 2023-05-30 01:54:07.246487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c4477e5623'
down_revision = 'a4d050f81a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('domain', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'domain')
    # ### end Alembic commands ###
