"""unit-parent

Revision ID: 7862fd6c810e
Revises: 975097c20b37
Create Date: 2024-12-10 08:17:47.630969

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '7862fd6c810e'
down_revision = '975097c20b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unit', 'unit', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.drop_column('unit', 'parent_id')
    # ### end Alembic commands ###
