"""event-pid

Revision ID: 7c5e4368cbef
Revises: 0dc9eae4c472
Create Date: 2024-06-12 08:08:52.746593

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '7c5e4368cbef'
down_revision = '0dc9eae4c472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('datetime_end', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pid_organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=500), nullable=True),
    sa.Column('pid_type', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('collection_name_key', 'collection', type_='unique')
    op.add_column('record', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'record', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_column('record', 'event_id')
    op.create_unique_constraint('collection_name_key', 'collection', ['name'])
    op.drop_table('pid_organization')
    op.drop_table('event')
    # ### end Alembic commands ###
