"""sync-multimedia

Revision ID: 7f2197958568
Revises: 833d766474dd
Create Date: 2023-12-29 06:40:41.197053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2197958568'
down_revision = '833d766474dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
