"""list-category-id2

Revision ID: 81810461634b
Revises: aacadc915bd8
Create Date: 2024-01-25 20:51:28.202527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81810461634b'
down_revision = 'aacadc915bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
