"""mo3

Revision ID: 833d766474dd
Revises: e5ecd2da6266
Create Date: 2023-12-27 10:13:56.300088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833d766474dd'
down_revision = 'e5ecd2da6266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multimedia_object', sa.Column('creator_text', sa.String(length=500), nullable=True))
    op.add_column('multimedia_object', sa.Column('provider_text', sa.String(length=500), nullable=True))
    op.drop_column('multimedia_object', 'creator')
    op.drop_column('multimedia_object', 'provider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multimedia_object', sa.Column('provider', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('multimedia_object', sa.Column('creator', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('multimedia_object', 'provider_text')
    op.drop_column('multimedia_object', 'creator_text')
    # ### end Alembic commands ###
