"""verbatim-collector

Revision ID: 8341c126c9bd
Revises: 76c4477e5623
Create Date: 2023-06-05 09:05:19.458681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8341c126c9bd'
down_revision = '76c4477e5623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('verbatim_collector', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'verbatim_collector')
    # ### end Alembic commands ###
