"""record_group

Revision ID: 8c3efecddd0a
Revises: 9141e26ebaa6
Create Date: 2024-10-22 02:25:31.468333

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '8c3efecddd0a'
down_revision = '9141e26ebaa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
