"""col_id index

Revision ID: 902ead9f65ec
Revises: d8f2a6a4b917
Create Date: 2023-06-14 17:54:22.211694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902ead9f65ec'
down_revision = 'd8f2a6a4b917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_record_collection_id'), 'record', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_collection_id'), table_name='record')
    # ### end Alembic commands ###
