"""annotation-mixin

Revision ID: 9096d76041b9
Revises: 9fbd514aeef2
Create Date: 2023-12-21 06:31:46.428501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9096d76041b9'
down_revision = '9fbd514aeef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('annotation_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annotation_type_id'], ['annotation_type.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('annotation_type', sa.Column('target', sa.String(length=50), nullable=True))
    op.add_column('annotation_type', sa.Column('sort', sa.Integer(), nullable=True))
    op.add_column('multimedia_object_annotation', sa.Column('annotation_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('multimedia_object_annotation_type_id_fkey', 'multimedia_object_annotation', type_='foreignkey')
    op.create_foreign_key(None, 'multimedia_object_annotation', 'annotation_type', ['annotation_type_id'], ['id'])
    op.drop_column('multimedia_object_annotation', 'type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multimedia_object_annotation', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'multimedia_object_annotation', type_='foreignkey')
    op.create_foreign_key('multimedia_object_annotation_type_id_fkey', 'multimedia_object_annotation', 'annotation_type', ['type_id'], ['id'])
    op.drop_column('multimedia_object_annotation', 'annotation_type_id')
    op.drop_column('annotation_type', 'sort')
    op.drop_column('annotation_type', 'target')
    op.drop_table('unit_annotation')
    # ### end Alembic commands ###
