"""record-group3

Revision ID: 9141e26ebaa6
Revises: 81921fd533d4
Create Date: 2024-10-21 11:00:49.709283

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '9141e26ebaa6'
down_revision = '81921fd533d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_group', sa.Column('category', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record_group', 'category')
    # ### end Alembic commands ###
