"""add source_id to taxon

Revision ID: 92854c1ee057
Revises: 582f972a840e
Create Date: 2026-03-24 00:31:54.596744

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '92854c1ee057'
down_revision = '582f972a840e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxon', sa.Column('source_id', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxon', 'source_id')
    # ### end Alembic commands ###
