"""unit-schema

Revision ID: 975097c20b37
Revises: 4ae271900f9c
Create Date: 2024-12-10 07:31:41.239253

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '975097c20b37'
down_revision = '4ae271900f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('tag_type', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('unit_mark')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_mark',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mark_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mark_text', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('mark_author', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mark_author'], ['person.id'], name='unit_mark_mark_author_fkey'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name='unit_mark_unit_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='unit_mark_pkey')
    )
    op.drop_table('tracking_tag')
    # ### end Alembic commands ###
