"""iden-verbatim_identifer

Revision ID: 9cb28bd40438
Revises: d3238a082e88
Create Date: 2024-07-10 03:20:49.703449

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = '9cb28bd40438'
down_revision = 'd3238a082e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identification', sa.Column('verbatim_identifier', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identification', 'verbatim_identifier')
    # ### end Alembic commands ###
