"""multimedia object adjust

Revision ID: 9fbd514aeef2
Revises: ff8d2ee7449b
Create Date: 2023-12-21 05:28:41.123825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fbd514aeef2'
down_revision = 'ff8d2ee7449b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multimedia_object', sa.Column('creator', sa.String(length=500), nullable=True))
    op.add_column('multimedia_object', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('multimedia_object', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.add_column('multimedia_object', sa.Column('created_by', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'multimedia_object', 'person', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'multimedia_object', 'person', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'multimedia_object', type_='foreignkey')
    op.drop_constraint(None, 'multimedia_object', type_='foreignkey')
    op.drop_column('multimedia_object', 'created_by')
    op.drop_column('multimedia_object', 'provider_id')
    op.drop_column('multimedia_object', 'creator_id')
    op.drop_column('multimedia_object', 'creator')
    # ### end Alembic commands ###
