"""multimedia-object

Revision ID: a1bf58983c76
Revises: 1fd9fdd0f070
Create Date: 2023-12-27 07:52:50.278167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1bf58983c76'
down_revision = '1fd9fdd0f070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multimedia_object_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('multimedia_object', sa.Column('reference', sa.String(length=500), nullable=True))
    op.add_column('multimedia_object', sa.Column('context', sa.String(length=500), nullable=True))
    op.add_column('multimedia_object', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('multimedia_object', sa.Column('license', sa.String(length=500), nullable=True))
    op.add_column('multimedia_object', sa.Column('rights_holder', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'multimedia_object', 'multimedia_object_category', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('multimedia_object', 'modified')
    op.drop_column('multimedia_object', 'created_by')
    op.drop_index('taxon_full_scientific_name', table_name='taxon')
    op.drop_index('taxon_rank', table_name='taxon')
    op.drop_index('taxon_relation_child_id', table_name='taxon_relation')
    op.drop_index('taxon_relation_parent_id', table_name='taxon_relation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('taxon_relation_parent_id', 'taxon_relation', ['parent_id'], unique=False)
    op.create_index('taxon_relation_child_id', 'taxon_relation', ['child_id'], unique=False)
    op.create_index('taxon_rank', 'taxon', ['rank'], unique=False)
    op.create_index('taxon_full_scientific_name', 'taxon', ['full_scientific_name'], unique=False)
    op.add_column('multimedia_object', sa.Column('created_by', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('multimedia_object', sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'multimedia_object', type_='foreignkey')
    op.drop_column('multimedia_object', 'rights_holder')
    op.drop_column('multimedia_object', 'license')
    op.drop_column('multimedia_object', 'category_id')
    op.drop_column('multimedia_object', 'context')
    op.drop_column('multimedia_object', 'reference')
    op.drop_table('multimedia_object_category')
    # ### end Alembic commands ###
