"""area-class admin_config

Revision ID: a8963344cf1f
Revises: 81810461634b
Create Date: 2024-01-26 14:45:01.820525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8963344cf1f'
down_revision = '81810461634b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area_class', sa.Column('admin_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area_class', 'admin_config')
    # ### end Alembic commands ###
