"""list-category-id

Revision ID: aacadc915bd8
Revises: 5eb6d18e0c1e
Create Date: 2024-01-25 19:47:02.215262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aacadc915bd8'
down_revision = '5eb6d18e0c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_list', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_list_user_list_category_fkey', 'user_list', type_='foreignkey')
    op.create_foreign_key(None, 'user_list', 'user_list_category', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('user_list', 'user_list_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_list', sa.Column('user_list_category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_list', type_='foreignkey')
    op.create_foreign_key('user_list_user_list_category_fkey', 'user_list', 'user_list_category', ['user_list_category'], ['id'], ondelete='SET NULL')
    op.drop_column('user_list', 'category_id')
    # ### end Alembic commands ###
