"""site_id

Revision ID: aef30cda76fc
Revises: b5a42e695eb4
Create Date: 2024-06-18 02:48:05.528842

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'aef30cda76fc'
down_revision = 'b5a42e695eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('site_id', sa.Integer(), nullable=True))
    op.drop_constraint('article_organization_id_fkey', 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'site', ['site_id'], ['id'], ondelete='SET NULL')
    op.drop_column('article', 'organization_id')
    op.add_column('article_category', sa.Column('site_id', sa.Integer(), nullable=True))
    op.drop_constraint('article_category_organization_id_fkey', 'article_category', type_='foreignkey')
    op.create_foreign_key(None, 'article_category', 'site', ['site_id'], ['id'], ondelete='SET NULL')
    op.drop_column('article_category', 'organization_id')
    op.add_column('related_link', sa.Column('site_id', sa.Integer(), nullable=True))
    op.drop_constraint('related_link_organization_id_fkey', 'related_link', type_='foreignkey')
    op.create_foreign_key(None, 'related_link', 'site', ['site_id'], ['id'], ondelete='SET NULL')
    op.drop_column('related_link', 'organization_id')
    op.add_column('related_link_category', sa.Column('site_id', sa.Integer(), nullable=True))
    op.drop_constraint('related_link_category_organization_id_fkey', 'related_link_category', type_='foreignkey')
    op.create_foreign_key(None, 'related_link_category', 'site', ['site_id'], ['id'], ondelete='SET NULL')
    op.drop_column('related_link_category', 'organization_id')
    op.add_column('user', sa.Column('site_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_organization_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'site', ['site_id'], ['id'], ondelete='SET NULL')
    op.drop_column('user', 'organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_organization_id_fkey', 'user', 'organization', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_column('user', 'site_id')
    op.add_column('related_link_category', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'related_link_category', type_='foreignkey')
    op.create_foreign_key('related_link_category_organization_id_fkey', 'related_link_category', 'organization', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_column('related_link_category', 'site_id')
    op.add_column('related_link', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'related_link', type_='foreignkey')
    op.create_foreign_key('related_link_organization_id_fkey', 'related_link', 'organization', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_column('related_link', 'site_id')
    op.add_column('article_category', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'article_category', type_='foreignkey')
    op.create_foreign_key('article_category_organization_id_fkey', 'article_category', 'organization', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_column('article_category', 'site_id')
    op.add_column('article', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key('article_organization_id_fkey', 'article', 'organization', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_column('article', 'site_id')
    # ### end Alembic commands ###
