"""record-na-assiciate2

Revision ID: b34921972c96
Revises: edabe202477f
Create Date: 2024-03-04 20:30:14.929427

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'b34921972c96'
down_revision = 'edabe202477f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
