"""taxon-clean-column

Revision ID: bafad5853ba5
Revises: cd358fbb3d95
Create Date: 2024-12-06 09:45:29.891651

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'bafad5853ba5'
down_revision = 'cd358fbb3d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('taxon_provider_id_fkey', 'taxon', type_='foreignkey')
    op.drop_column('taxon', 'author_parenthesis')
    op.drop_column('taxon', 'provider_source_id')
    op.drop_column('taxon', 'provider_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxon', sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('taxon', sa.Column('provider_source_id', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('taxon', sa.Column('author_parenthesis', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key('taxon_provider_id_fkey', 'taxon', 'taxon_provider', ['provider_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
