"""unit-cover-image

Revision ID: bd8fe670a01d
Revises: 8c3efecddd0a
Create Date: 2024-11-03 05:41:32.999968

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'bd8fe670a01d'
down_revision = '8c3efecddd0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('cover_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unit', 'multimedia_object', ['cover_image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.drop_column('unit', 'cover_image_id')
    # ### end Alembic commands ###
