"""unit-note

Revision ID: c42d7991b1ed
Revises: 2d3ac4882c24
Create Date: 2025-11-25 21:15:16.104342

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'c42d7991b1ed'
down_revision = '2d3ac4882c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_note_unit_id'), 'unit_note', ['unit_id'], unique=False)
    op.create_index(op.f('ix_unit_note_user_id'), 'unit_note', ['user_id'], unique=False)
    op.drop_constraint(op.f('record_group_map_record_id_fkey'), 'record_group_map', type_='foreignkey')
    op.create_foreign_key(None, 'record_group_map', 'record', ['record_id'], ['id'])
    op.add_column('unit', sa.Column('verbatim_label', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'verbatim_label')
    op.drop_constraint(None, 'record_group_map', type_='foreignkey')
    op.create_foreign_key(op.f('record_group_map_record_id_fkey'), 'record_group_map', 'record', ['record_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_unit_note_user_id'), table_name='unit_note')
    op.drop_index(op.f('ix_unit_note_unit_id'), table_name='unit_note')
    op.drop_table('unit_note')
    # ### end Alembic commands ###
