"""site.data

Revision ID: c80f91a5fba6
Revises: 3785ccd6eb37
Create Date: 2024-06-18 08:42:35.128037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'c80f91a5fba6'
down_revision = '3785ccd6eb37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'data')
    # ### end Alembic commands ###
