"""taxon-specific-epith

Revision ID: cd358fbb3d95
Revises: 23812df96b5f
Create Date: 2024-12-06 09:38:59.686549

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'cd358fbb3d95'
down_revision = '23812df96b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxon', sa.Column('specific_epithet', sa.String(length=500), nullable=True))
    op.drop_column('taxon', 'first_epithet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxon', sa.Column('first_epithet', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('taxon', 'specific_epithet')
    # ### end Alembic commands ###
