"""collection_taxon_map

Revision ID: cf68a46997e3
Revises: 92854c1ee057
Create Date: 2026-03-25 08:34:16.746066

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'cf68a46997e3'
down_revision = '92854c1ee057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_taxon_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('taxon_tree_id', sa.Integer(), nullable=False),
    sa.Column('taxon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxon_id'], ['taxon.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxon_tree_id'], ['taxon_tree.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_taxon_map_collection_id'), 'collection_taxon_map', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_taxon_map_collection_id'), table_name='collection_taxon_map')
    op.drop_table('collection_taxon_map')
    # ### end Alembic commands ###
