"""[schema]user.role & identification

Revision ID: d3238a082e88
Revises: 54844ef10da8
Create Date: 2024-07-08 20:08:07.792777

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'd3238a082e88'
down_revision = '54844ef10da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('verbatim_collect_date', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('record', 'verbatim_collect_date')
    # ### end Alembic commands ###
