"""org-add-scope

Revision ID: d8f2a6a4b917
Revises: 8341c126c9bd
Create Date: 2023-06-06 09:53:49.359853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f2a6a4b917'
down_revision = '8341c126c9bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('taxonomic_scope', sa.String(length=1000), nullable=True))
    op.add_column('organization', sa.Column('geographic_scope', sa.String(length=1000), nullable=True))
    op.add_column('organization', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'description')
    op.drop_column('organization', 'geographic_scope')
    op.drop_column('organization', 'taxonomic_scope')
    # ### end Alembic commands ###
