"""[schema] type_is_published

Revision ID: deba9932caca
Revises: 7a60049f9f0f
Create Date: 2023-03-29 03:01:13.651169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deba9932caca'
down_revision = '7a60049f9f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('type_is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'type_is_published')
    # ### end Alembic commands ###
