"""record-named-area-map-via

Revision ID: e1fda716c3ec
Revises: 5b41d404cb3b
Create Date: 2024-03-04 18:29:22.760739

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'e1fda716c3ec'
down_revision = '5b41d404cb3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('protect_area_geom_idx', table_name='protect_area', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('protect_area')
    op.drop_geospatial_table('town_majia_sanhe')
    op.drop_geospatial_table('wild_1043')
    op.drop_geospatial_index('village_nlsc_1120317_geom_idx', table_name='village_nlsc_1120317', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('village_nlsc_1120317')
    op.drop_geospatial_table('town_moi_1120825')
    op.drop_geospatial_index('county_moi_1090820_geom_idx', table_name='county_moi_1090820', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('county_moi_1090820')
    op.drop_geospatial_table('world_administrative_boundaries')
    op.add_column('record_named_area_map', sa.Column('via', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record_named_area_map', 'via')
    op.create_geospatial_table('world_administrative_boundaries',
    sa.Column('gid', sa.INTEGER(), server_default=sa.text('nextval(\'"world-administrative-boundaries_gid_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('iso3', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('color_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('continent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('iso_3166_1_', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('french_shor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name='world-administrative-boundaries_pkey')
    )
    op.create_geospatial_table('county_moi_1090820',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('countyid', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('countycode', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('countyname', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('countyeng', sa.VARCHAR(length=39), autoincrement=False, nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name='county_moi_1090820_pkey')
    )
    op.create_geospatial_index('county_moi_1090820_geom_idx', 'county_moi_1090820', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('town_moi_1120825',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('townid', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('towncode', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('countyname', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('townname', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('towneng', sa.VARCHAR(length=39), autoincrement=False, nullable=True),
    sa.Column('countyid', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('countycode', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name='town_moi_1120825_pkey')
    )
    op.create_geospatial_table('village_nlsc_1120317',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('villcode', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    sa.Column('countyname', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('townname', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('villname', sa.VARCHAR(length=39), autoincrement=False, nullable=True),
    sa.Column('villeng', sa.VARCHAR(length=39), autoincrement=False, nullable=True),
    sa.Column('countyid', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('countycode', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('townid', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('towncode', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name='village_nlsc_1120317_pkey')
    )
    op.create_geospatial_index('village_nlsc_1120317_geom_idx', 'village_nlsc_1120317', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('wild_1043',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('c_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('shape_leng', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('shape_area', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name='wild_1043_pkey')
    )
    op.create_geospatial_table('town_majia_sanhe',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('townid', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('towncode', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('countyname', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('townname', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('towneng', sa.VARCHAR(length=39), autoincrement=False, nullable=True),
    sa.Column('countyid', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('countycode', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name='town_majia_sanhe_pkey')
    )
    op.create_geospatial_table('protect_area',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('shape_leng', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('announce', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('area_ha', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('id', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('shape_star', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('shape_stle', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name='protect_area_pkey')
    )
    op.create_geospatial_index('protect_area_geom_idx', 'protect_area', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###
