"""recard-named-area-map cascade

Revision ID: e508c32e9e09
Revises: 9cb28bd40438
Create Date: 2024-10-16 03:19:19.478626

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'e508c32e9e09'
down_revision = '9cb28bd40438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('record_named_area_map_record_id_fkey', 'record_named_area_map', type_='foreignkey')
    op.create_foreign_key(None, 'record_named_area_map', 'record', ['record_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record_named_area_map', type_='foreignkey')
    op.create_foreign_key('record_named_area_map_record_id_fkey', 'record_named_area_map', 'record', ['record_id'], ['id'])
    # ### end Alembic commands ###
