"""vol-task

Revision ID: e54d405a9b1c
Revises: c42d7991b1ed
Create Date: 2025-12-16 02:55:38.689216

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'e54d405a9b1c'
down_revision = 'c42d7991b1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_task_assigned_by_id'), 'volunteer_task', ['assigned_by_id'], unique=False)
    op.create_index(op.f('ix_volunteer_task_status'), 'volunteer_task', ['status'], unique=False)
    op.create_index(op.f('ix_volunteer_task_unit_id'), 'volunteer_task', ['unit_id'], unique=True)
    op.create_index(op.f('ix_volunteer_task_volunteer_id'), 'volunteer_task', ['volunteer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_task_volunteer_id'), table_name='volunteer_task')
    op.drop_index(op.f('ix_volunteer_task_unit_id'), table_name='volunteer_task')
    op.drop_index(op.f('ix_volunteer_task_status'), table_name='volunteer_task')
    op.drop_index(op.f('ix_volunteer_task_assigned_by_id'), table_name='volunteer_task')
    op.drop_table('volunteer_task')
    # ### end Alembic commands ###
