"""mo-remove-source

Revision ID: e5ecd2da6266
Revises: 280914e94b3e
Create Date: 2023-12-27 09:42:06.898465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ecd2da6266'
down_revision = '280914e94b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('multimedia_object', 'source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multimedia_object', sa.Column('source', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
