"""site

Revision ID: eda150eeea0c
Revises: deba9932caca
Create Date: 2023-05-29 17:18:42.431586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda150eeea0c'
down_revision = 'deba9932caca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('is_site', sa.Boolean(), nullable=True))
    op.add_column('organization', sa.Column('subdomain', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'subdomain')
    op.drop_column('organization', 'is_site')
    # ### end Alembic commands ###
