"""record-na-assiciate

Revision ID: edabe202477f
Revises: e1fda716c3ec
Create Date: 2024-03-04 19:50:52.439762

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'edabe202477f'
down_revision = 'e1fda716c3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
