"""add hierarchy jsonb to taxon_tree

Revision ID: f41778c0817e
Revises: d1e2f3a4b5c6
Create Date: 2026-03-13 04:07:13.351058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'f41778c0817e'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record_person', 'role')
    op.add_column('taxon_tree', sa.Column('hierarchy', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxon_tree', 'hierarchy')
    op.add_column('record_person', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
