"""org.other-name

Revision ID: f49ffdecf4ff
Revises: d73728d72d3a
Create Date: 2023-03-25 03:45:56.240640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49ffdecf4ff'
down_revision = 'd73728d72d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('other_name', sa.String(length=500), nullable=True))
    op.add_column('organization', sa.Column('website_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'website_url')
    op.drop_column('organization', 'other_name')
    # ### end Alembic commands ###
