"""add site_id to person

Revision ID: f5ecbe5589ed
Revises: 5a005bedbbbc
Create Date: 2026-03-03 08:10:00.120056

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'f5ecbe5589ed'
down_revision = '5a005bedbbbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'person', 'site', ['site_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'site_id')
    # ### end Alembic commands ###
