"""accession-number

Revision ID: f64687dde625
Revises: a273a1d5455d
Create Date: 2023-01-22 13:08:08.307025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64687dde625'
down_revision = 'a273a1d5455d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'catalog_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('catalog_number', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
