"""area-class-conf

Revision ID: fb2dd663057f
Revises: 242c03df73fc
Create Date: 2024-02-20 08:41:18.912879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2dd663057f'
down_revision = '242c03df73fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
