"""[SCHEMA] collection.multimedia_object add some field and multimedia_object_annotation

Revision ID: ff8d2ee7449b
Revises: 120c3695c90e
Create Date: 2023-12-21 01:20:29.357595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8d2ee7449b'
down_revision = '120c3695c90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multimedia_object_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('multimedia_object_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['multimedia_object_id'], ['multimedia_object.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['annotation_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('multimedia_object', sa.Column('record_id', sa.Integer(), nullable=True))
    op.add_column('multimedia_object', sa.Column('physical_format', sa.String(length=500), nullable=True))
    op.add_column('multimedia_object', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('multimedia_object', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('multimedia_object', sa.Column('modified', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'multimedia_object', 'record', ['record_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'multimedia_object', type_='foreignkey')
    op.drop_column('multimedia_object', 'modified')
    op.drop_column('multimedia_object', 'date_created')
    op.drop_column('multimedia_object', 'thumbnail_url')
    op.drop_column('multimedia_object', 'physical_format')
    op.drop_column('multimedia_object', 'record_id')
    op.drop_table('multimedia_object_annotation')
    # ### end Alembic commands ###
