ARG POSTGRES_VERSION
ARG DEBIAN_RELEASE

FROM postgres:${POSTGRES_VERSION}-${DEBIAN_RELEASE}

ARG POSTGRES_VERSION

RUN apt-get update \
      && apt-get install -y --no-install-recommends \
          postgresql-${POSTGRES_VERSION}-postgis-3 \
          postgresql-${POSTGRES_VERSION}-postgis-3-scripts \
          postgis \
      && rm -rf /var/lib/apt/lists/*