"""anno-data

Revision ID: 1f96c9f1b0e8
Revises: 9536e841b8b9
Create Date: 2023-03-22 19:33:21.938150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f96c9f1b0e8'
down_revision = '9536e841b8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_type', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('unit', sa.Column('pub_status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'pub_status')
    op.drop_column('annotation_type', 'data')
    # ### end Alembic commands ###
