"""annotation

Revision ID: 576b4583425b
Revises: 
Create Date: 2023-03-21 07:08:15.705792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576b4583425b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('annotation_unit_id_fkey', 'annotation', type_='foreignkey')
    op.create_foreign_key(None, 'annotation', 'unit', ['unit_id'], ['id'])
    op.add_column('annotation_type', sa.Column('input_type', sa.String(length=50), nullable=True))
    op.drop_column('unit', 'pub_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('pub_status', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('annotation_type', 'input_type')
    op.drop_constraint(None, 'annotation', type_='foreignkey')
    op.create_foreign_key('annotation_unit_id_fkey', 'annotation', 'unit', ['unit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
